name: Docker Image CI

on:
  workflow_run:
    workflows: ["Snake-Game Build and Test"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_PASSWORD
      - name: Build
        run: docker build . --file Dockerfile
        
      - name: Push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/snake-game:latest
